sudo: false
language: php
dist: trusty

php:
        - 7.0
        - 7.1
        - nightly

matrix:
        allow_failures:
                - php: nightly


addons:
        apt:
                sources:
                        - llvm-toolchain-trusty-5.0
                        - ubuntu-toolchain-r-test
                packages:
                        - clang-5.0
                        - g++-6

before_script:
        - phpize
        - CC=clang-5.0 CXX=clang++-5.0 ./configure
        - make
        - make install
        - echo "extension=parle.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
        - REPORT_EXIT_STATUS=1 php ./run-tests.php -P -q --show-diff

