sudo: false
language: php
dist: trusty

php:
        - 7.3
        - 7.4
        - 8.0 
        - nightly

matrix:
        allow_failures:
                - php: nightly

env:
        matrix:
                - UTF32=0
                - UTF32=1


addons:
        apt:
                sources:
                        #- llvm-toolchain-trusty-5.0
                        - ubuntu-toolchain-r-test
                packages:
                        #- clang-5.0
                        #- g++-6
                        - g++-5

before_script:
        - phpize
          #- CC=clang-5.0 CXX=clang++-5.0 ./configure
          #- CC=gcc-6 CXX=g++-6 ./configure
        - if test $UTF32 = 1; then CC=gcc-5 CXX=g++-5 ./configure --enable-parle-utf32; else CC=gcc-5 CXX=g++-5 ./configure; fi
        - make
        - make install
        - echo "extension=parle.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
        - REPORT_EXIT_STATUS=1 php ./run-tests.php -P -q --show-diff

