sudo: false
language: php
dist: trusty

php:
        - 7.0
        - 7.1
        - nightly

matrix:
        allow_failures:
                - php: nightly
        include:
                - os: linux
                  addons:
                    apt:
                      sources:
                        - ubuntu-toolchain-r-test
                      packages:
                        - g++-5
                  env:
                      - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

before_script:
        - phpize
        - ./configure
        - make
        - make install
        - echo "extension=parle.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
        - REPORT_EXIT_STATUS=1 php ./run-tests.php -P -q --show-diff

