name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        operating-system: ['ubuntu-18.04']
        php-versions: ['7.4', '8.0', '8.1']
        utf32: [1, 0]
        gcc-versions: ['5', '9', '11']
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v2
      - uses: egor-tensin/setup-gcc@v1
        with:
          version: ${{ matrix.gcc-versions }}
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
      - run: phpize
      - run: |
          if test ${{ matrix.utf32 }} = 1; then UTF32_OPT=--enable-parle-utf32; fi
          CC=gcc-${{ matrix.gcc-versions }} CXX=g++-${{ matrix.gcc-versions }} ./configure $UTF32_OPT
      - run: make
      - run: make test TESTS="-P -q --show-diff"

